#ifndef DRIVERSAMPLE_GLOBAL_H
#define DRIVERSAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRIVERSAMPLE_LIBRARY)
#  define DRIVERSAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DRIVERSAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DRIVERSAMPLE_GLOBAL_H
